<?php

/**
 * @file
 * Admin Form for SLA Calculations
 */
function sla_calculations_menu() {

  $items = array();

  $items['admin/config/sla-calculations/index'] = array(
        'title' => 'SLA Calculations Options',
        'description' => 'This module is designed for calculate time between two dates.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('form_admin_sla_calculations_main'),
        'access arguments' => array('access sla calculations'),
        'file' => 'form_admin_sla_calculations_main.inc',
        'type' => MENU_NORMAL_ITEM,
        'weight' => -15,
  );

    return $items;

}

function sla_calculations_permission() {
  return array(
    'access sla calculations' => array(
      'title' => t('Permisson for SLA Calculations'),
    )
  );
}

/*
* Implemmenting hook_page_build
* https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_page_build/7.x
*/
function sla_calculations_page_build() {
  $path = drupal_get_path('module', 'sla_calculations');
  drupal_add_css($path . '/sla_calculations.css');
}


/*
* Implemmenting hook_theme
* https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_theme/7.x
*/
function sla_calculations_theme() {
    return array(
    'sla_calculations_full' => array(
      'template' => 'sla_calculations_full',
    ),
    'sla_calculations_middle' => array(
      'template' => 'sla_calculations_middle',
    ),
    'sla_calculations_min' => array(
      'template' => 'sla_calculations_min',
    )
  );
}


/*
*
*
*/
function sla_calculations_block_info() {

  $blocks['sla_calculations_full'] = array(
    'info' => 'SLA Calculations Full',
  );

  $blocks['sla_calculations_middle'] = array(
    'info' => 'SLA Calculations Middle',
  );

  $blocks['sla_calculations_min'] = array(
    'info' => 'SLA Calculations Min',
  );

  return $blocks;

}


/*
*
*
*/
function sla_calculations_block_view($delta = '') {

     $block = array();
     $block['subject'] = '';

     //The $delta parameter tells us which block is being requested.
     switch ($delta) {
         case 'sla_calculations_full':
             // Create your block content here
             $block['subject'] = t('My last 3 news');

             $arrayContentType = array();
             $arrayContentType[] = 'alcaldias';
             $arrayContentType[] = 'article';
             $arrayContentType[] = 'audio';
             $arrayContentType[] = 'autor_blog';
             $arrayContentType[] = 'autor_nota';
             $arrayContentType[] = 'cartera';
             $arrayContentType[] = 'carton';
             $arrayContentType[] = 'chats';
             $arrayContentType[] = 'marquee';
             $arrayContentType[] = 'panopoly_page';

             $arrayContentType[] = 'deportes_widget_opta';
             $arrayContentType[] = 'deportes_widget_video';
             $arrayContentType[] = 'elecciones_2017_coahuila';
             $arrayContentType[] = 'elecciones_2017_nayarit';
             $arrayContentType[] = 'elecciones_2017_veracruz';
             $arrayContentType[] = 'elecciones_2018_gobernador';
             $arrayContentType[] = 'elecciones_2018_partidos';
             $arrayContentType[] = 'elecciones_2018_presidente_';
             $arrayContentType[] = 'page';
             $arrayContentType[] = 'emprendedor';
             $arrayContentType[] = 'entrada_de_blog';
             $arrayContentType[] = 'opinion';
             $arrayContentType[] = 'tema_caliente';
             $arrayContentType[] = 'especial_detalle';
             $arrayContentType[] = 'especiales';
             $arrayContentType[] = 'event_calendar';

             $arrayContentType[] = 'event_calendar';
             $arrayContentType[] = 'feed';
             $arrayContentType[] = 'feed_item';
             $arrayContentType[] = 'galeria';
             $arrayContentType[] = 'grafico';
             $arrayContentType[] = 'hoy_no_circula';

             $arrayContentType[] = 'include';
             $arrayContentType[] = 'manuales';
             $arrayContentType[] = 'minuto_x_minuto';
             $arrayContentType[] = 'podcast';
             $arrayContentType[] = 'promo_4_videos';
             $arrayContentType[] = 'promo_chiapas';
             $arrayContentType[] = 'promo_df';
             $arrayContentType[] = 'promo_sitio_01';
             $arrayContentType[] = 'promo_edomex';
             $arrayContentType[] = 'promo_sitio_02';


             $arrayContentType[] = 'promo_oaxaca';
             $arrayContentType[] = 'promo_sitio_03';
             $arrayContentType[] = 'promo_sitio_05';
             $arrayContentType[] = 'promo_san_luis';
             $arrayContentType[] = 'promo_veracruz';
             $arrayContentType[] = 'promo_sitio_04';
             $arrayContentType[] = 'promo_central_universo_deportivo';
             $arrayContentType[] = 'promo_cintillo_superior';
             $arrayContentType[] = 'promo_ediciones_impresas';
             $arrayContentType[] = 'promo_revistas_flipping_book';

             $arrayContentType[] = 'promo_inf_el_botiquin';
             $arrayContentType[] = 'promo_inf_universo_deportivo';
             $arrayContentType[] = 'promo_notas_externas';
             $arrayContentType[] = 'promo_columna';
             $arrayContentType[] = 'promo_revistas';
             $arrayContentType[] = 'promo_revistas_fondo_';
             $arrayContentType[] = 'promo_universo_deportivo';
             $arrayContentType[] = 'promo';
             $arrayContentType[] = 'promo_video_superior';
             $arrayContentType[] = 'reporte_lector';
             $arrayContentType[] = 'servicios_apps';
             $arrayContentType[] = 'serivicios_clima_estados';
             $arrayContentType[] = 'servicios_club_sms';
             $arrayContentType[] = 'servicios_hor_scopos';
             $arrayContentType[] = 'trust_author';

             $arrayContentType[] = 'trust_reference';
             $arrayContentType[] = 'video';
             $arrayContentType[] = 'voz_del_lector';
             $arrayContentType[] = 'borra';
             $arrayContentType[] = 'image';
             $arrayContentType[] = 'promo_sitio_union';

             $arrayContentType[] = 'promo_blog';
             $arrayContentType[] = 'promo_externo_central';
             $arrayContentType[] = 'promo_externo_lateral';
             $arrayContentType[] = 'promo_suplementos';


             $query = new EntityFieldQuery();
             //change news by the name of your content type
             $query->entityCondition('entity_type', 'node')
             //->entityCondition('bundle', 'article')
             ->propertyCondition('type', 'article')
             ->propertyCondition('status', 1)
             //
             ->propertyOrderBy("created", "DESC")
             ->range(0, 10);
             //->execute()
             $result = $query->execute();
             //$count  = $query->count()->execute();
             //$result = $query->execute();
             $block['content'] = "<h1>sla_calculations_full</h1>";
             //$block['content'] .= "Count: " . print_r($result);
             //$block['content'] =  "<pre>" . $result . "</pre>";
             foreach($result['node'] as $obj){
                 //$block['content'] .= " => " . $obj ."<br>";
                 $node = node_load($obj->nid);
                 $block['content'] .= l( $node->title, "node/" . $node->nid ) . ' - ' . date('d-m-Y h:m:s', $node->created) . '<br>';
             }

             /*
             * Test of Time
             */

             $mtime = microtime();
             $mtime = explode(" ",$mtime);
             $mtime = $mtime[1] + $mtime[0];
             $starttime = $mtime;

             date_default_timezone_set("America/Mexico_City");

             $dateTime = " Last Update: " . date("h:i:sa");

             $FI = "2019-01-01 03:09:47";
             $FF = "2019-04-25 14:44:42";

             $SLACalculations = 0;

              $block['content'] .= "tmpFI: ".$FI."</br>";
              $block['content'] .= "tmpFF: ".$FF."</br>";


             for ($date = strtotime($FI); $date < strtotime($FF); $date = strtotime("+1 day", $date)){
                    $block['content'] .= date("Y-m-d", $date)."<br/>";
                    //echo date("Y-m-d", $date)." isWeekend= ".isWeekend($date." 00:00:00")."<br/>";
                    //if(isWeekend($date) == 0){
                    //     echo date("Y-m-d", $date)."<br/>";
                    //}
             }

             //
             $urlImage = drupal_get_path('module', 'sla_calculations') . "/graficoSLAtime.php";
             $block['content'] .= $dateTime;
             $block['content'] .= '<div align="center"><img src="'.$urlImage.'"></div>';
             //$block['content'] .= ;

             $totalItems = 0;
             foreach ($arrayContentType as $key => $value) {
                 $total = getTotalNodesByMachineName($value);
                 $block['content'] .= " Result Total ". $value .": " . $total . "<br/>";
                 $totalItems = $totalItems + $total;
                 //$block['content'] .= " Result Total: ". $key . "<br/>";
             }

             $block['content'] .= " Total: " . $totalItems;

         break;

         case 'sla_calculations_middle':

             $dateTime = " Last Update: " . date("h:i:sa");
             $urlImage = drupal_get_path('module', 'sla_calculations') . "/grafico-01.php";
             $block['content'] = "<h1>SLA GRAPH</h1>";
             $block['content'] .= $dateTime;
             $block['content'] .= '<div align="center"><img src="'.$urlImage.'"></div>';

         break;


         case 'sla_calculations_min':


             $block['content'] = "<h1>sla_calculations_min</h1>";
             $dateTime = " Last Update: " . date("h:i:sa");
             $urlImage = drupal_get_path('module', 'sla_calculations') . "/grafico-02.php";
             $block['content'] = "<h1>SLA GRAPH</h1>";
             $block['content'] .= $dateTime;
             $block['content'] .= '<div align="center"><img src="'.$urlImage.'"></div>';

             //Prueba de campos en array


         break;

     }

     return $block;
}



function getTotalNodesByMachineName($contentType){

  //Total Nodos
  $queryTotal = new EntityFieldQuery();

  $queryTotal->entityCondition('entity_type', 'node') // grab nodes
  ->entityCondition('bundle', $contentType) // filter by blog type
  ->propertyCondition('status', 1) // filter by published
  ->count(); // count

  $resultTotal = $queryTotal->execute();

  return $resultTotal;

}
